spring:
  application:
    name: springbootdemo
  datasource:
    url: jdbc:mysql://hadoop02:3306/java_interview?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 120653
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: caffeine
    cache-names:
      - user_cache
      - product_cache
    caffeine:
      # spec 字符串定义：最大容量，写入后过期时间
      spec: maximumSize=500,expireAfterWrite=600s

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yiban.springbootdemo.entity
  configuration:
    map-underscore-to-camel-case: true